version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: "15.3.0"  # Update to the version your project requires
    working_directory: ~/project

    steps:
      - checkout

      # 🔧 Install dependencies if you're using CocoaPods
      - run:
          name: Install CocoaPods
          command: |
            if [ -f Podfile ]; then
              sudo gem install cocoapods
              pod install
            fi

      # Build the app
      - run:
          name: Build App
          command: |
            xcodebuild \
              -workspace CodeChallange.xcworkspace \
              -scheme CodeChallange \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
              clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      # Run unit tests (including snapshot/UI)
      - run:
          name: Run Tests
          command: |
            xcodebuild \
              -workspace CodeChallange.xcworkspace \
              -scheme CodeChallange \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
              clean test \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

workflows:
  ios:
    jobs:
      - build-and-test
